# SPDX-FileCopyrightText: © 2025 Eashwar Ranganathan <eashwar@eashwar.com>
# SPDX-License-Identifier: MIT

[package]
name = "faster-geohash"
version = "0.2.0"
authors = ["Eashwar Ranganathan <eashwar@eashwar.com>"]
edition = "2024"
rust-version = "1.95"

description = "A fast geohashing library"
readme = "README.md"
license = "MIT"
keywords = ["geohash", "gis"]

# This rust code only exists to bind with python
# It should not be published as a crate
publish = false

[dependencies]
geohash = "0.13.2"
pyo3 = "0.29"

[features]
# This feature allows for building abi3 compatible wheels, but is not enabled by default
# here or in the maturin config. Enable it explicitly when building the wheel, e.g.
# `uv build -C maturin.build-args=--features=abi3 --wheel .`
# Keep the `pyo3/abi3-{lower_bound}` feature here in sync with project.requires-python in the pyproject.toml
abi3 = [
	"pyo3/abi3",
	"pyo3/abi3-py310",  # tag::MIN_PYTHON
]

[build-dependencies]
pyo3-build-config = { version = "0.29.2", features = ["resolve-config"] }

[lib]
name = "faster_geohash"
crate-type = ["cdylib"]
path = "src/lib.rs"


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
