def encode(coords: tuple[float, float], /, precision: int = 12) -> str: ...
def decode_bbox(hash_str: str) -> tuple[tuple[float, float], tuple[float, float]]: ...
def decode_exact(hash_str: str) -> tuple[tuple[float, float], float, float]: ...
def decode(hash_str: str) -> tuple[str, str]: ...
